package common.model;

import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.Objects;

/**
 * Organization stored in the server collection.
 */
public class Organization implements Serializable, Comparable<Organization>, Validatable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String name;
    private final Coordinates coordinates;
    private final ZonedDateTime creationDate;
    private final int annualTurnover;
    private final long employeesCount;
    private final OrganizationType type;
    private final Address officialAddress;

    /**
     * Creates an organization.
     *
     * @param id generated id, must be unique and positive in stored objects
     * @param name non-empty name
     * @param coordinates non-null coordinates
     * @param creationDate generated creation date in stored objects
     * @param annualTurnover annual turnover, must be positive
     * @param employeesCount employee count, must be positive
     * @param type optional organization type
     * @param officialAddress non-null official address
     */
    public Organization(Integer id,
                        String name,
                        Coordinates coordinates,
                        ZonedDateTime creationDate,
                        int annualTurnover,
                        long employeesCount,
                        OrganizationType type,
                        Address officialAddress) {
        this.id = id;
        this.name = name;
        this.coordinates = coordinates;
        this.creationDate = creationDate;
        this.annualTurnover = annualTurnover;
        this.employeesCount = employeesCount;
        this.type = type;
        this.officialAddress = officialAddress;
    }

    /**
     * Returns a copy with server-generated fields.
     *
     * @param newId positive id generated by the server
     * @param newCreationDate creation date generated by the server
     * @return organization copy
     */
    public Organization withGenerated(Integer newId, ZonedDateTime newCreationDate) {
        return new Organization(newId, name, coordinates, newCreationDate,
                annualTurnover, employeesCount, type, officialAddress);
    }

    public Integer getId() { return id; }
    public String getName() { return name; }
    public Coordinates getCoordinates() { return coordinates; }
    public ZonedDateTime getCreationDate() { return creationDate; }
    public int getAnnualTurnover() { return annualTurnover; }
    public long getEmployeesCount() { return employeesCount; }
    public OrganizationType getType() { return type; }
    public Address getOfficialAddress() { return officialAddress; }

    /**
     * Validates fields that are entered by the user before server-generated
     * fields are assigned.
     *
     * @return true if all user-entered fields satisfy the task constraints
     */
    public boolean validateWithoutGeneratedFields() {
        return name != null && !name.trim().isEmpty()
                && coordinates != null && coordinates.validate()
                && annualTurnover > 0
                && employeesCount > 0
                && officialAddress != null && officialAddress.validate();
    }

    @Override
    public boolean validate() {
        return id != null && id > 0
                && creationDate != null
                && validateWithoutGeneratedFields();
    }

    /**
     * Natural order for lab commands. Generated fields are intentionally not
     * the primary key here, so commands that accept a temporary element can be
     * evaluated before the server assigns id and creationDate.
     */
    @Override
    public int compareTo(Organization other) {
        if (other == null) {
            return 1;
        }
        int cmp = this.name.compareTo(other.name);
        if (cmp != 0) {
            return cmp;
        }
        cmp = Integer.compare(this.annualTurnover, other.annualTurnover);
        if (cmp != 0) {
            return cmp;
        }
        cmp = Long.compare(this.employeesCount, other.employeesCount);
        if (cmp != 0) {
            return cmp;
        }
        int thisId = this.id == null ? 0 : this.id;
        int otherId = other.id == null ? 0 : other.id;
        return Integer.compare(thisId, otherId);
    }

    @Override
    public String toString() {
        return "Organization{"
                + "id=" + id
                + ", name='" + name + '\''
                + ", coordinates=" + coordinates
                + ", creationDate=" + creationDate
                + ", annualTurnover=" + annualTurnover
                + ", employeesCount=" + employeesCount
                + ", type=" + type
                + ", officialAddress=" + officialAddress
                + '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Organization that)) {
            return false;
        }
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
